APP_PLATFORM := android-16
APP_ABI := armeabi-v7a
APP_ABI += x86
APP_ABI += x86_64
#APP_ABI += mips
APP_ABI += arm64-v8a
NDK_TOOLCHAIN_VERSION = clang
APP_STL := c++_static
APP_ALLOW_MISSING_DEPS :=true